# Generated by Django 4.1.5 on 2023-01-27 01:54

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockingDensity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('verdict', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(db_column='date_joined', default=django.utils.timezone.now)),
            ],
        ),
    ]
