# Generated by Django 4.1.5 on 2023-01-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockright', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockingdensity',
            options={'ordering': ['-created'], 'verbose_name_plural': 'stocking densities'},
        ),
        migrations.AddField(
            model_name='stockingdensity',
            name='to_stock',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
