# Generated by Django 4.1.5 on 2023-01-27 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockright', '0002_alter_stockingdensity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockingdensity',
            name='created',
            field=models.DateTimeField(db_column='date_checked', default=django.utils.timezone.now),
        ),
    ]
