# Generated by Django 4.1.5 on 2023-05-21 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockright', '0003_alter_stockingdensity_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockingdensity',
            options={'ordering': ['-date_checked'], 'verbose_name': 'stocking density', 'verbose_name_plural': 'stocking densities'},
        ),
        migrations.RemoveField(
            model_name='stockingdensity',
            name='created',
        ),
        migrations.AddField(
            model_name='stockingdensity',
            name='date_checked',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 21, 14, 49, 43, 550796, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
