# Generated by Django 4.2.1 on 2023-09-06 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockright', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockingdensity',
            options={'ordering': ['-date_added'], 'verbose_name': 'stocking density', 'verbose_name_plural': 'stocking densities'},
        ),
        migrations.RenameField(
            model_name='stockingdensity',
            old_name='date_checked',
            new_name='date_added',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
