# Generated by Django 4.1.5 on 2023-05-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockright', '0004_alter_stockingdensity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stockingdensity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='stockingdensity',
            name='pond',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockright.pond'),
            preserve_default=False,
        ),
    ]
