# Generated by Django 4.2.1 on 2023-05-23 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockright', '0005_pond_alter_stockingdensity_id_stockingdensity_pond'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
