# Generated by Django 4.2.1 on 2023-09-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockright', '0005_alter_stockingdensity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
