# Generated by Django 4.2.1 on 2023-09-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockright', '0006_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
