# Generated by Django 4.2.1 on 2023-05-31 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockright', '0006_pond_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pond',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockingdensity',
            name='date_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
