# Generated by Django 4.2.1 on 2023-06-03 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockright', '0007_alter_pond_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockingdensity',
            name='height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='stockingdensity',
            name='length',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
        migrations.AlterField(
            model_name='stockingdensity',
            name='width',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
    ]
