# Generated by Django 4.2.1 on 2023-06-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockright', '0009_alter_stockingdensity_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockingdensity',
            name='thirty_percent_increase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockingdensity',
            name='twenty_percent_increase',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
