# Generated by Django 4.2.1 on 2023-09-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockright', '0009_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
