# Generated by Django 4.2.1 on 2023-06-16 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockright', '0011_rename_thirty_percent_increase_stockingdensity_thirty_percent_decrease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pond',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to=settings.AUTH_USER_MODEL),
        ),
    ]
