# Generated by Django 4.2.1 on 2023-06-17 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockright', '0012_alter_pond_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
