# Generated by Django 4.2.1 on 2023-06-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockright', '0014_stockingdensity_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockingdensity',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockingdensity',
            name='width',
            field=models.FloatField(),
        ),
    ]
